version: "3.8"

services:
  db:
    build:
      context: ./build/db
      dockerfile: Dockerfile
    ports:
      - 54330:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
  queue:
    image: library/rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
  app:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    environment:
      SERVER_PORT: 9091
    env_file:
      - build/env/local/.env
    ports:
      - 9091:9091
    depends_on:
      - db
      - queue
  app-test:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    environment:
      SERVER_PORT: 9092
    env_file:
      - build/env/test/.env
    ports:
      - 9092:9092
    depends_on:
      - db
      - queue

volumes:
  db-data: