version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 54330:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  queue:
    image: library/rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      SERVER_PORT: 9091
    env_file:
      - .env
    ports:
      - 9091:9091
    depends_on:
      - db
      - queue

volumes:
  db-data: