// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/oleglarionov/otusgolang_finalproject/internal/grpc"
	"github.com/oleglarionov/otusgolang_finalproject/internal/grpc/generated"
)

// Injectors from wire.go:

func setup(cfg Config) (*App, error) {
	bannerRotationServerImpl := internalgrpc.NewBannerRotationServerImpl()
	server := grpcServerProvider(cfg, bannerRotationServerImpl)
	app := NewApp(server)
	return app, nil
}

// wire.go:

func grpcServerProvider(cfg Config, service grpcgenerated.BannerRotationServiceServer) *internalgrpc.Server {
	return internalgrpc.NewServer(cfg.ServerPort, service)
}
